# coding: utf-8

"""
    HiRes API

    Back office API for NAFI HiRes burnt areas mapping and tasking

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from ntrrp.hires_client.models.acquisition_response_mirbi_dataset import (
    AcquisitionResponseMirbiDataset,
)
from ntrrp.hires_client.models.acquisition_response_natural_colour_dataset import (
    AcquisitionResponseNaturalColourDataset,
)
from ntrrp.hires_client.models.sentinel2_tile_response import Sentinel2TileResponse
from typing import Optional, Set
from typing_extensions import Self


class AcquisitionResponse(BaseModel):
    """
    AcquisitionResponse
    """  # noqa: E501

    uuid: StrictStr
    var_date: datetime = Field(alias="date")
    sentinel2_tiles: List[Sentinel2TileResponse]
    natural_colour_dataset: AcquisitionResponseNaturalColourDataset
    mirbi_dataset: AcquisitionResponseMirbiDataset
    __properties: ClassVar[List[str]] = [
        "uuid",
        "date",
        "sentinel2_tiles",
        "natural_colour_dataset",
        "mirbi_dataset",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AcquisitionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sentinel2_tiles (list)
        _items = []
        if self.sentinel2_tiles:
            for _item in self.sentinel2_tiles:
                if _item:
                    _items.append(_item.to_dict())
            _dict["sentinel2_tiles"] = _items
        # override the default output from pydantic by calling `to_dict()` of natural_colour_dataset
        if self.natural_colour_dataset:
            _dict["natural_colour_dataset"] = self.natural_colour_dataset.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mirbi_dataset
        if self.mirbi_dataset:
            _dict["mirbi_dataset"] = self.mirbi_dataset.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AcquisitionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "uuid": obj.get("uuid"),
                "date": obj.get("date"),
                "sentinel2_tiles": (
                    [
                        Sentinel2TileResponse.from_dict(_item)
                        for _item in obj["sentinel2_tiles"]
                    ]
                    if obj.get("sentinel2_tiles") is not None
                    else None
                ),
                "natural_colour_dataset": (
                    AcquisitionResponseNaturalColourDataset.from_dict(
                        obj["natural_colour_dataset"]
                    )
                    if obj.get("natural_colour_dataset") is not None
                    else None
                ),
                "mirbi_dataset": (
                    AcquisitionResponseMirbiDataset.from_dict(obj["mirbi_dataset"])
                    if obj.get("mirbi_dataset") is not None
                    else None
                ),
            }
        )
        return _obj
