# coding: utf-8

"""
    HiRes API

    Back office API for NAFI HiRes burnt areas mapping and tasking

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from ntrrp.hires_client.models.acquisition_response import AcquisitionResponse
from ntrrp.hires_client.models.difference_response_difference_acquisition import (
    DifferenceResponseDifferenceAcquisition,
)
from ntrrp.hires_client.models.difference_response_dmirbi_dataset import (
    DifferenceResponseDmirbiDataset,
)
from ntrrp.hires_client.models.segmentation_dataset_response import (
    SegmentationDatasetResponse,
)
from typing import Optional, Set
from typing_extensions import Self


class DifferenceResponse(BaseModel):
    """
    DifferenceResponse
    """  # noqa: E501

    uuid: StrictStr
    var_date: datetime = Field(alias="date")
    difference_date: datetime
    code: StrictInt
    difference_code: StrictInt
    segmentation_datasets: List[SegmentationDatasetResponse]
    acquisition: AcquisitionResponse
    difference_acquisition: DifferenceResponseDifferenceAcquisition
    dmirbi_dataset: DifferenceResponseDmirbiDataset
    __properties: ClassVar[List[str]] = [
        "uuid",
        "date",
        "difference_date",
        "code",
        "difference_code",
        "segmentation_datasets",
        "acquisition",
        "difference_acquisition",
        "dmirbi_dataset",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DifferenceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in segmentation_datasets (list)
        _items = []
        if self.segmentation_datasets:
            for _item in self.segmentation_datasets:
                if _item:
                    _items.append(_item.to_dict())
            _dict["segmentation_datasets"] = _items
        # override the default output from pydantic by calling `to_dict()` of acquisition
        if self.acquisition:
            _dict["acquisition"] = self.acquisition.to_dict()
        # override the default output from pydantic by calling `to_dict()` of difference_acquisition
        if self.difference_acquisition:
            _dict["difference_acquisition"] = self.difference_acquisition.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dmirbi_dataset
        if self.dmirbi_dataset:
            _dict["dmirbi_dataset"] = self.dmirbi_dataset.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DifferenceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "uuid": obj.get("uuid"),
                "date": obj.get("date"),
                "difference_date": obj.get("difference_date"),
                "code": obj.get("code"),
                "difference_code": obj.get("difference_code"),
                "segmentation_datasets": (
                    [
                        SegmentationDatasetResponse.from_dict(_item)
                        for _item in obj["segmentation_datasets"]
                    ]
                    if obj.get("segmentation_datasets") is not None
                    else None
                ),
                "acquisition": (
                    AcquisitionResponse.from_dict(obj["acquisition"])
                    if obj.get("acquisition") is not None
                    else None
                ),
                "difference_acquisition": (
                    DifferenceResponseDifferenceAcquisition.from_dict(
                        obj["difference_acquisition"]
                    )
                    if obj.get("difference_acquisition") is not None
                    else None
                ),
                "dmirbi_dataset": (
                    DifferenceResponseDmirbiDataset.from_dict(obj["dmirbi_dataset"])
                    if obj.get("dmirbi_dataset") is not None
                    else None
                ),
            }
        )
        return _obj
