# coding: utf-8

"""
    HiRes API

    Back office API for NAFI HiRes burnt areas mapping and tasking

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from ntrrp.hires_client.models.acquisition_response import AcquisitionResponse
from ntrrp.hires_client.models.difference_response import DifferenceResponse
from ntrrp.hires_client.models.region_response import RegionResponse
from typing import Optional, Set
from typing_extensions import Self


class MappingResponse(BaseModel):
    """
    MappingResponse
    """  # noqa: E501

    uuid: StrictStr
    var_date: datetime = Field(alias="date")
    region: RegionResponse
    acquisitions: List[AcquisitionResponse]
    differences: List[DifferenceResponse]
    __properties: ClassVar[List[str]] = [
        "uuid",
        "date",
        "region",
        "acquisitions",
        "differences",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MappingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of region
        if self.region:
            _dict["region"] = self.region.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in acquisitions (list)
        _items = []
        if self.acquisitions:
            for _item in self.acquisitions:
                if _item:
                    _items.append(_item.to_dict())
            _dict["acquisitions"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in differences (list)
        _items = []
        if self.differences:
            for _item in self.differences:
                if _item:
                    _items.append(_item.to_dict())
            _dict["differences"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MappingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "uuid": obj.get("uuid"),
                "date": obj.get("date"),
                "region": (
                    RegionResponse.from_dict(obj["region"])
                    if obj.get("region") is not None
                    else None
                ),
                "acquisitions": (
                    [
                        AcquisitionResponse.from_dict(_item)
                        for _item in obj["acquisitions"]
                    ]
                    if obj.get("acquisitions") is not None
                    else None
                ),
                "differences": (
                    [
                        DifferenceResponse.from_dict(_item)
                        for _item in obj["differences"]
                    ]
                    if obj.get("differences") is not None
                    else None
                ),
            }
        )
        return _obj
