# coding: utf-8

"""
    HiRes API

    Back office API for NAFI HiRes burnt areas mapping and tasking

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TaskType(str, Enum):
    """
    TaskType
    """

    """
    allowed enum values
    """
    ACQUIRE_SENTINEL2 = "acquire_sentinel2"
    DEFAULT = "default"
    LOAD_SEGMENTATION = "load_segmentation"
    LOAD_TEST_DATA = "load_test_data"
    UNLOAD_TEST_DATA = "unload_test_data"
    RESTART_TEGOLA = "restart_tegola"
    REWRITE_TEGOLA_CONFIGURATION = "rewrite_tegola_configuration"
    RESTART_MARTIN = "restart_martin"
    REWRITE_MARTIN_CONFIGURATION = "rewrite_martin_configuration"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TaskType from a JSON string"""
        return cls(json.loads(json_str))
