# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Nafi
                                 A QGIS plugin
 Northern Australia Fire & Rangelands Map Services
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-28
        copyright            : (C) 2020 by Tom Lynch
        email                : tom@trailmarker.io
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Nafi class from file Nafi.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nafi import Nafi
    return Nafi(iface)
