# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NafiDockWidget
                                 A QGIS plugin
 Northern Australia Fire & Rangelands Map Services
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-28
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Tom Lynch
        email                : tom@trailmarker.io
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from urllib import parse

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal, QRegExp, QSortFilterProxyModel, Qt, QModelIndex
from qgis.PyQt.QtGui import QFont, QStandardItem, QStandardItemModel 
from qgis.PyQt.QtWidgets import QApplication, QMessageBox

from qgis.core import QgsRasterLayer, QgsProject

from owslib.wms import WebMapService
from owslib.map.wms111 import ContentMetadata, WebMapService_1_1_1

from .nafi_dockwidget_base import Ui_NafiDockWidgetBase

NAFI_URL = "https://www.firenorth.org.au/public"
UNWANTED_LAYERS = ["NODATA_RASTER"]

def groupByRootLayers(layers):
    """Reconstruct the parent-child relationships in an OWSLib ContentMetadata tree."""
    parents = {}
    for layer in layers:
        if layer.parent != None:
            if layer.parent.title not in parents:
                parents[layer.parent.title] = layer.parent
                layer.parent.children = [layer]
            elif not any(c.title == layer.title for c in parents[layer.parent.title].children): 
                parents[layer.parent.title].children.append(layer)
        else:
            parents[layer.title] = layer

    parentLayers = list(parents.values())
    if (len(parentLayers) == len(layers)):
        return parentLayers
    else: 
        return groupByRootLayers(parentLayers)

def addLayerToViewModel(model, owsLayer, unwantedLayers = []):
    """Add an OWSLib layer to a QStandardItemModel, potentially with descendant layers and 
       using a list of 'blacklisted' layer names, to a QStandardItemModel."""
    assert isinstance(model, QStandardItem) or isinstance(model, QStandardItemModel)
    assert isinstance(owsLayer, ContentMetadata)

    layersList = {}

    node = QStandardItem()
    node.setFlags(Qt.ItemIsEnabled)
    node.setText(owsLayer.title)

    if owsLayer.title not in unwantedLayers:
        model.appendRow(node)
        # track all these OWS ContentMetadata objects by title for a reverse lookup
        layersList[owsLayer.title] = owsLayer
        # add children to view model
        for childLayer in owsLayer.children:
            # merge layersList entries from children
            layersList.update(addLayerToViewModel(node, childLayer, unwantedLayers))
    else:
        pass

    return layersList

class NafiDockWidget(QtWidgets.QDockWidget, Ui_NafiDockWidgetBase):
    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(NafiDockWidget, self).__init__(parent)
        
        self.setupUi(self)
        self.treeView.pressed.connect(self.handleTreeViewPressed)
        self.lineEdit.textChanged.connect(self.searchTextChanged)
        
        self.loadLayers()

    def loadLayers(self):
        """Add all NAFI WMS layers."""
        nafiUrl = NAFI_URL
        self.wms = WebMapService(nafiUrl)

        self.layersList = {}
        
        # set up base model
        self.treeViewModel = QStandardItemModel()

        # set up proxy model for filtering        
        self.proxyModel = QSortFilterProxyModel(self.treeView)
        self.proxyModel.setSourceModel(self.treeViewModel)
        self.proxyModel.setRecursiveFilteringEnabled(True)
        self.treeView.setModel(self.proxyModel)

        # set up QTreeView        
        self.treeView.setHeaderHidden(True)
        self.treeView.setSortingEnabled(True)
        self.treeView.pressed.connect(self.handleTreeViewPressed)
        
        # set up search signal
        self.lineEdit.textChanged.connect(self.searchTextChanged)
        
        # initialise model from WMS contents
        self.initModel(self.wms)

    def initModel(self, wms):
        """Initialise a QStandardItemModel from the NAFI WMS."""
        # check we've got the expected WMS protocol from NAFI
        assert isinstance(wms, WebMapService_1_1_1)
        # this structure is not properly organised via its "children" properties, need to fix it up
        owsLayers = [wms.contents[layerName] for layerName in list(wms.contents)]

        # check we've got at least one layer
        assert (len(owsLayers) > 0)

        # calculate our root layer
        rootLayer = groupByRootLayers(owsLayers)[0]
        # create model
        self.layersList = addLayerToViewModel(self.treeViewModel, rootLayer, UNWANTED_LAYERS)

    def handleTreeViewPressed(self, index):
        """Load a NAFI WMS layer given an index in the tree view."""
        assert isinstance(index, QModelIndex), "Supplied parameter is not a QModelIndex"

        realIndex = self.proxyModel.mapToSource(index)
        modelNode = self.treeViewModel.itemFromIndex(realIndex)
        layer = self.layersList[modelNode.text()]
       
        # If we've got a WMS layer and not a layer group, add to map
        if len(layer.children) == 0:
            wmsLayer = self.createWmsLayer(layer)
            QgsProject.instance().addMapLayer(wmsLayer)

    def createWmsLayer(self, owsLayer):
        """Create a QgsRasterLayer from WMS given an OWS ContentMetadata object."""
        assert isinstance(owsLayer, ContentMetadata)

        # Weirdly true URL-encoding of the layer ID does not work correctly
        encodedLayer = owsLayer.id.replace(" ","%20")

        # This should create "EPSG:28350" for Map Grid of Australia, "EPSG:4326" for WGS84 etc
        encodedSrsId = f"EPSG:{QgsProject.instance().crs().postgisSrid()}"
        wmsUrl = f"crs={encodedSrsId}&format=image/png&layers={encodedLayer}&styles&url={NAFI_URL}"
        wmsLayer = QgsRasterLayer(wmsUrl, owsLayer.title, 'wms')
        return wmsLayer

    def searchTextChanged(self, text):
        """Process a change in the search filter text."""
        regex = QRegExp(text, Qt.CaseInsensitive, QRegExp.RegExp)
        self.proxyModel.setFilterRegExp(regex)
        self.treeView.expandAll()

    def closeEvent(self, event):
        """Handle plug-in close."""
        self.closingPlugin.emit()
        event.accept()
