"""
    HiRes API

    Back office API for NAFI HiRes burnt areas mapping and tasking  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from nafi_hires.hires_client.api_client import ApiClient, Endpoint as _Endpoint
from nafi_hires.hires_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from nafi_hires.hires_client.model.approve_segmentation_features import ApproveSegmentationFeatures
from nafi_hires.hires_client.model.http_validation_error import HTTPValidationError
from nafi_hires.hires_client.model.refresh_tiles_response import RefreshTilesResponse
from nafi_hires.hires_client.model.reject_segmentation_features import RejectSegmentationFeatures


class SegmentationApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.approve_segmentation_v1_segmentation_approve_mapping_uuid_segmentation_dataset_uuid_post_endpoint = _Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str, none_type,),
                'auth': [],
                'endpoint_path': '/v1/segmentation/approve/{mapping_uuid}/{segmentation_dataset_uuid}',
                'operation_id': 'approve_segmentation_v1_segmentation_approve_mapping_uuid_segmentation_dataset_uuid_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'mapping_uuid',
                    'segmentation_dataset_uuid',
                    'approve_segmentation_features',
                ],
                'required': [
                    'mapping_uuid',
                    'segmentation_dataset_uuid',
                    'approve_segmentation_features',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'mapping_uuid':
                        (str,),
                    'segmentation_dataset_uuid':
                        (str,),
                    'approve_segmentation_features':
                        (ApproveSegmentationFeatures,),
                },
                'attribute_map': {
                    'mapping_uuid': 'mapping_uuid',
                    'segmentation_dataset_uuid': 'segmentation_dataset_uuid',
                },
                'location_map': {
                    'mapping_uuid': 'path',
                    'segmentation_dataset_uuid': 'path',
                    'approve_segmentation_features': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.get_proxy_tileserver_v1_segmentation_tiles_path_get_endpoint = _Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str, none_type,),
                'auth': [],
                'endpoint_path': '/v1/segmentation/tiles/{path}',
                'operation_id': 'get_proxy_tileserver_v1_segmentation_tiles_path_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'path',
                ],
                'required': [
                    'path',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'path':
                        (str,),
                },
                'attribute_map': {
                    'path': 'path',
                },
                'location_map': {
                    'path': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.head_proxy_tileserver_v1_segmentation_tiles_path_head_endpoint = _Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str, none_type,),
                'auth': [],
                'endpoint_path': '/v1/segmentation/tiles/{path}',
                'operation_id': 'head_proxy_tileserver_v1_segmentation_tiles_path_head',
                'http_method': 'HEAD',
                'servers': None,
            },
            params_map={
                'all': [
                    'path',
                ],
                'required': [
                    'path',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'path':
                        (str,),
                },
                'attribute_map': {
                    'path': 'path',
                },
                'location_map': {
                    'path': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.reject_segmentation_v1_segmentation_reject_mapping_uuid_segmentation_dataset_uuid_post_endpoint = _Endpoint(
            settings={
                'response_type': (RefreshTilesResponse,),
                'auth': [],
                'endpoint_path': '/v1/segmentation/reject/{mapping_uuid}/{segmentation_dataset_uuid}',
                'operation_id': 'reject_segmentation_v1_segmentation_reject_mapping_uuid_segmentation_dataset_uuid_post',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'mapping_uuid',
                    'segmentation_dataset_uuid',
                    'reject_segmentation_features',
                ],
                'required': [
                    'mapping_uuid',
                    'segmentation_dataset_uuid',
                    'reject_segmentation_features',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'mapping_uuid':
                        (str,),
                    'segmentation_dataset_uuid':
                        (str,),
                    'reject_segmentation_features':
                        (RejectSegmentationFeatures,),
                },
                'attribute_map': {
                    'mapping_uuid': 'mapping_uuid',
                    'segmentation_dataset_uuid': 'segmentation_dataset_uuid',
                },
                'location_map': {
                    'mapping_uuid': 'path',
                    'segmentation_dataset_uuid': 'path',
                    'reject_segmentation_features': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )

    def approve_segmentation_v1_segmentation_approve_mapping_uuid_segmentation_dataset_uuid_post(
        self,
        mapping_uuid,
        segmentation_dataset_uuid,
        approve_segmentation_features,
        **kwargs
    ):
        """Approve Segmentation  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.approve_segmentation_v1_segmentation_approve_mapping_uuid_segmentation_dataset_uuid_post(mapping_uuid, segmentation_dataset_uuid, approve_segmentation_features, async_req=True)
        >>> result = thread.get()

        Args:
            mapping_uuid (str):
            segmentation_dataset_uuid (str):
            approve_segmentation_features (ApproveSegmentationFeatures):

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            bool, date, datetime, dict, float, int, list, str, none_type
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['mapping_uuid'] = \
            mapping_uuid
        kwargs['segmentation_dataset_uuid'] = \
            segmentation_dataset_uuid
        kwargs['approve_segmentation_features'] = \
            approve_segmentation_features
        return self.approve_segmentation_v1_segmentation_approve_mapping_uuid_segmentation_dataset_uuid_post_endpoint.call_with_http_info(**kwargs)

    def get_proxy_tileserver_v1_segmentation_tiles_path_get(
        self,
        path,
        **kwargs
    ):
        """Get Proxy Tileserver  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_proxy_tileserver_v1_segmentation_tiles_path_get(path, async_req=True)
        >>> result = thread.get()

        Args:
            path (str):

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            bool, date, datetime, dict, float, int, list, str, none_type
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['path'] = \
            path
        return self.get_proxy_tileserver_v1_segmentation_tiles_path_get_endpoint.call_with_http_info(**kwargs)

    def head_proxy_tileserver_v1_segmentation_tiles_path_head(
        self,
        path,
        **kwargs
    ):
        """Head Proxy Tileserver  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.head_proxy_tileserver_v1_segmentation_tiles_path_head(path, async_req=True)
        >>> result = thread.get()

        Args:
            path (str):

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            bool, date, datetime, dict, float, int, list, str, none_type
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['path'] = \
            path
        return self.head_proxy_tileserver_v1_segmentation_tiles_path_head_endpoint.call_with_http_info(**kwargs)

    def reject_segmentation_v1_segmentation_reject_mapping_uuid_segmentation_dataset_uuid_post(
        self,
        mapping_uuid,
        segmentation_dataset_uuid,
        reject_segmentation_features,
        **kwargs
    ):
        """Reject Segmentation  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.reject_segmentation_v1_segmentation_reject_mapping_uuid_segmentation_dataset_uuid_post(mapping_uuid, segmentation_dataset_uuid, reject_segmentation_features, async_req=True)
        >>> result = thread.get()

        Args:
            mapping_uuid (str):
            segmentation_dataset_uuid (str):
            reject_segmentation_features (RejectSegmentationFeatures):

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            RefreshTilesResponse
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['mapping_uuid'] = \
            mapping_uuid
        kwargs['segmentation_dataset_uuid'] = \
            segmentation_dataset_uuid
        kwargs['reject_segmentation_features'] = \
            reject_segmentation_features
        return self.reject_segmentation_v1_segmentation_reject_mapping_uuid_segmentation_dataset_uuid_post_endpoint.call_with_http_info(**kwargs)

