# flake8: noqa

"""
    HiRes API

    Back office API for NAFI HiRes burnt areas mapping and tasking  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from nafi_hires.hires_client.api_client import ApiClient

# import Configuration
from nafi_hires.hires_client.configuration import Configuration

# import exceptions
from nafi_hires.hires_client.exceptions import OpenApiException
from nafi_hires.hires_client.exceptions import ApiAttributeError
from nafi_hires.hires_client.exceptions import ApiTypeError
from nafi_hires.hires_client.exceptions import ApiValueError
from nafi_hires.hires_client.exceptions import ApiKeyError
from nafi_hires.hires_client.exceptions import ApiException
