# flake8: noqa

"""
    HiRes API

    Back office API for NAFI HiRes burnt areas mapping and tasking  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from ntrrp.hires_client.api_client import ApiClient

# import Configuration
from ntrrp.hires_client.configuration import Configuration

# import exceptions
from ntrrp.hires_client.exceptions import OpenApiException
from ntrrp.hires_client.exceptions import ApiAttributeError
from ntrrp.hires_client.exceptions import ApiTypeError
from ntrrp.hires_client.exceptions import ApiValueError
from ntrrp.hires_client.exceptions import ApiKeyError
from ntrrp.hires_client.exceptions import ApiException
